Use pytket visualization methods in notebooks
CQCL/pytket pull request #101
Opened 2021-09-06 14:30 UTC by yao-cqc

2021-09-07 07:23 UTC, cqc-alec requested changes
I think there is one more example in `conditional_gate_example.py` to change.

I think we should emphasise, in the commentary in `circuit_analysis_example.py`, that the `render_circuit_jupyter` method only works in a browser context. Otherwise (in scripts or python shells) one of the other methods should be used.

2021-09-07 10:13 UTC, yao-cqc commented
> I think there is one more example in `conditional_gate_example.py` to change.

I thought that one was to showcase the qiskit converter according to this [comment](https://github.com/CQCL/pytket/blob/265dc809c1eba24ca7890b76a3e06d58d5f13343/examples/python/conditional_gate_example.py#L94)?

> I think we should emphasise, in the commentary in circuit_analysis_example.py, that the render_circuit_jupyter method only works in a browser context. Otherwise (in scripts or python shells) one of the other methods should be used.

Make sense, I'm going to make the change.

2021-09-07 10:23 UTC, cqc-alec commented
> > I think there is one more example in `conditional_gate_example.py` to change.
> 
> I thought that one was to showcase the qiskit converter according to this [comment](https://github.com/CQCL/pytket/blob/265dc809c1eba24ca7890b76a3e06d58d5f13343/examples/python/conditional_gate_example.py#L94)?

Ah yes you are right.

2021-09-15 09:01 UTC, cqc-alec approved these changes

2021-09-15 09:06 UTC, merged