Release/1.6.0
CQCL/pytket pull request #170
Opened 2022-09-07 14:29 UTC by cqc-melf

update pytket to 1.6 and pytket-quanitnuum 0.8.0

2022-09-09 15:56 UTC, cqc-melf commented
> regression

Thank you, if you can confirm that this is not an issue in the notebook I an take over the investigations of the issue in tket, too.

2022-09-10 07:45 UTC, cqc-alec commented
This is a bug in TKET: https://github.com/CQCL/tket/issues/514 .

2022-09-10 08:32 UTC, cqc-alec requested changes
Maybe we should wait for a hotfix to pytket rather than lower the optimization level on the passes here.

2022-09-10 08:32 UTC, cqc-alec commented on examples/python/comparing_simulators.py
> +    if i != j:
This is unnecessary: `combinations()` returns pairs of distinct values.

2022-09-12 08:39 UTC, cqc-melf commented
I will close this and make a new PR with pytket 11.6.1

2022-09-12 08:39 UTC, closed without merging